table.insert(_defaultJobData, {
	Type = "Company",
	LastUpdated = 1784524361,
	Id = "tuna",
	Name = "Tuner Shop",
	Salary = 700,
	SalaryTier = 1,
	Grades = {
		{
			Id = "mechanic",
			Name = "Mechanic",
			Level = 1,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				FLEET_VEHICLES_0 = true,
				TABLET_TWEET = false,
			},
		},
		{
			Id = "headmechanic",
			Name = "Head Mechanic",
			Level = 2,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				FLEET_VEHICLES_0 = true,
			},
		},
		{
			Id = "owner",
			Name = "Owner",
			Level = 99,
			Permissions = {
				JOB_MANAGEMENT = true,
				BANK_ACCOUNT_MANAGE = true,
				BANK_ACCOUNT_WITHDRAW = true,
				BANK_ACCOUNT_DEPOSIT = true,
				BANK_ACCOUNT_TRANSACTIONS = true,
				BANK_ACCOUNT_BILL = true,
				BANK_ACCOUNT_BALANCE = true,
				JOB_MANAGE_EMPLOYEES = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				TABLET_TWEET = true,
				FLEET_VEHICLES_0 = true,
				FLEET_MANAGEMENT = true,
			},
		},
	},
})

table.insert(_defaultJobData, {
	Type = "Company",
	LastUpdated = 1784524361,
	Id = "redline",
	Name = "Redline",
	Salary = 700,
	SalaryTier = 1,
	Grades = {
		{
			Id = "mechanic",
			Name = "Mechanic",
			Level = 1,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				FLEET_VEHICLES_0 = true,
				TABLET_TWEET = false,
			},
		},
		{
			Id = "headmechanic",
			Name = "Head Mechanic",
			Level = 2,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				FLEET_VEHICLES_0 = true,
			},
		},
		{
			Id = "owner",
			Name = "Owner",
			Level = 99,
			Permissions = {
				JOB_MANAGEMENT = true,
				BANK_ACCOUNT_MANAGE = true,
				BANK_ACCOUNT_WITHDRAW = true,
				BANK_ACCOUNT_DEPOSIT = true,
				BANK_ACCOUNT_TRANSACTIONS = true,
				BANK_ACCOUNT_BILL = true,
				BANK_ACCOUNT_BALANCE = true,
				JOB_MANAGE_EMPLOYEES = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				TABLET_TWEET = true,
				FLEET_VEHICLES_0 = true,
				FLEET_MANAGEMENT = true,
			},
		},
	},
})

table.insert(_defaultJobData, {
	Type = "Company",
	LastUpdated = 1784524361,
	Id = "blackline",
	Name = "Blackline Mechanics",
	Salary = 700,
	SalaryTier = 1,
	Hidden = true,
	Grades = {
		{
			Id = "mechanic",
			Name = "Mechanic",
			Level = 1,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				FLEET_VEHICLES_0 = true,
				TABLET_TWEET = false,
			},
		},
		{
			Id = "owner",
			Name = "Owner",
			Level = 99,
			Permissions = {
				JOB_MANAGEMENT = true,
				BANK_ACCOUNT_MANAGE = true,
				BANK_ACCOUNT_WITHDRAW = true,
				BANK_ACCOUNT_DEPOSIT = true,
				BANK_ACCOUNT_TRANSACTIONS = true,
				BANK_ACCOUNT_BILL = true,
				BANK_ACCOUNT_BALANCE = true,
				JOB_MANAGE_EMPLOYEES = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				TABLET_TWEET = true,
				FLEET_VEHICLES_0 = true,
				FLEET_MANAGEMENT = true,
			},
		},
	},
})

table.insert(_defaultJobData, {
	Type = "Company",
	LastUpdated = 1784524361,
	Id = "tirenutz",
	Name = "Tire Nutz",
	Salary = 700,
	SalaryTier = 1,
	Grades = {
		{
			Id = "mechanic",
			Name = "Mechanic",
			Level = 1,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				FLEET_VEHICLES_0 = true,
				TABLET_TWEET = false,
			},
		},
		{
			Id = "headmechanic",
			Name = "Head Mechanic",
			Level = 2,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				FLEET_VEHICLES_0 = true,
			},
		},
		{
			Id = "owner",
			Name = "Owner",
			Level = 99,
			Permissions = {
				JOB_MANAGEMENT = true,
				BANK_ACCOUNT_MANAGE = true,
				BANK_ACCOUNT_WITHDRAW = true,
				BANK_ACCOUNT_DEPOSIT = true,
				BANK_ACCOUNT_TRANSACTIONS = true,
				BANK_ACCOUNT_BILL = true,
				BANK_ACCOUNT_BALANCE = true,
				JOB_MANAGE_EMPLOYEES = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				TABLET_TWEET = true,
				FLEET_VEHICLES_0 = true,
				FLEET_MANAGEMENT = true,
			},
		},
	},
})

table.insert(_defaultJobData, {
	Type = "Company",
	LastUpdated = 1784524361,
	Id = "hayes",
	Name = "Hayes Autos",
	Salary = 700,
	SalaryTier = 1,
	Grades = {
		{
			Id = "mechanic",
			Name = "Mechanic",
			Level = 1,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				TABLET_TWEET = false,
				FLEET_VEHICLES_0 = true,
			},
		},
		{
			Id = "headmechanic",
			Name = "Head Mechanic",
			Level = 2,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				FLEET_VEHICLES_0 = true,
			},
		},
		{
			Id = "owner",
			Name = "Owner",
			Level = 99,
			Permissions = {
				JOB_MANAGEMENT = true,
				BANK_ACCOUNT_MANAGE = true,
				BANK_ACCOUNT_WITHDRAW = true,
				BANK_ACCOUNT_DEPOSIT = true,
				BANK_ACCOUNT_TRANSACTIONS = true,
				BANK_ACCOUNT_BILL = true,
				BANK_ACCOUNT_BALANCE = true,
				JOB_MANAGE_EMPLOYEES = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				TABLET_TWEET = true,
				FLEET_VEHICLES_0 = true,
				FLEET_MANAGEMENT = true,
			},
		},
	},
})

table.insert(_defaultJobData, {
	Type = "Company",
	LastUpdated = 1784524361,
	Id = "atomic",
	Name = "Atomic Mechanics",
	Salary = 700,
	SalaryTier = 1,
	Grades = {
		{
			Id = "mechanic",
			Name = "Mechanic",
			Level = 1,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				TABLET_TWEET = false,
				FLEET_VEHICLES_0 = true,
			},
		},
		{
			Id = "headmechanic",
			Name = "Head Mechanic",
			Level = 2,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				FLEET_VEHICLES_0 = true,
			},
		},
		{
			Id = "owner",
			Name = "Owner",
			Level = 99,
			Permissions = {
				JOB_MANAGEMENT = true,
				BANK_ACCOUNT_MANAGE = true,
				BANK_ACCOUNT_WITHDRAW = true,
				BANK_ACCOUNT_DEPOSIT = true,
				BANK_ACCOUNT_TRANSACTIONS = true,
				BANK_ACCOUNT_BILL = true,
				BANK_ACCOUNT_BALANCE = true,
				JOB_MANAGE_EMPLOYEES = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				TABLET_TWEET = true,
				FLEET_VEHICLES_0 = true,
				FLEET_MANAGEMENT = true,
			},
		},
	},
})

table.insert(_defaultJobData, {
	Type = "Company",
	LastUpdated = 1784524361,
	Id = "harmony",
	Name = "Harmony Repairs",
	Salary = 700,
	SalaryTier = 1,
	Grades = {
		{
			Id = "mechanic",
			Name = "Mechanic",
			Level = 1,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				FLEET_VEHICLES_0 = true,
				TABLET_TWEET = false,
			},
		},
		{
			Id = "headmechanic",
			Name = "Head Mechanic",
			Level = 2,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				FLEET_VEHICLES_0 = true,
			},
		},
		{
			Id = "owner",
			Name = "Owner",
			Level = 99,
			Permissions = {
				JOB_MANAGEMENT = true,
				BANK_ACCOUNT_MANAGE = true,
				BANK_ACCOUNT_WITHDRAW = true,
				BANK_ACCOUNT_DEPOSIT = true,
				BANK_ACCOUNT_TRANSACTIONS = true,
				BANK_ACCOUNT_BILL = true,
				BANK_ACCOUNT_BALANCE = true,
				JOB_MANAGE_EMPLOYEES = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				TABLET_TWEET = true,
				FLEET_VEHICLES_0 = true,
				FLEET_MANAGEMENT = true,
			},
		},
	},
})

table.insert(_defaultJobData, {
	Type = "Company",
	LastUpdated = 1784524361,
	Id = "superperformance",
	Name = "Super Performance",
	Salary = 700,
	SalaryTier = 1,
	Grades = {
		{
			Id = "mechanic",
			Name = "Mechanic",
			Level = 1,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				TABLET_TWEET = false,
				FLEET_VEHICLES_0 = true,
			},
		},
		{
			Id = "headmechanic",
			Name = "Head Mechanic",
			Level = 2,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				FLEET_VEHICLES_0 = true,
			},
		},
		{
			Id = "owner",
			Name = "Owner",
			Level = 99,
			Permissions = {
				JOB_MANAGEMENT = true,
				BANK_ACCOUNT_MANAGE = true,
				BANK_ACCOUNT_WITHDRAW = true,
				BANK_ACCOUNT_DEPOSIT = true,
				BANK_ACCOUNT_TRANSACTIONS = true,
				BANK_ACCOUNT_BILL = true,
				BANK_ACCOUNT_BALANCE = true,
				JOB_MANAGE_EMPLOYEES = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				TABLET_TWEET = true,
				FLEET_VEHICLES_0 = true,
				FLEET_MANAGEMENT = true,
			},
		},
	},
})

table.insert(_defaultJobData, {
	Type = "Company",
	LastUpdated = 1784524361,
	Id = "autoexotics",
	Name = "Auto Exotics",
	Salary = 700,
	SalaryTier = 1,
	Grades = {
		{
			Id = "mechanic",
			Name = "Mechanic",
			Level = 1,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				TABLET_TWEET = false,
				FLEET_VEHICLES_0 = true,
			},
		},
		{
			Id = "headmechanic",
			Name = "Head Mechanic",
			Level = 2,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				FLEET_VEHICLES_0 = true,
			},
		},
		{
			Id = "owner",
			Name = "Owner",
			Level = 99,
			Permissions = {
				JOB_MANAGEMENT = true,
				BANK_ACCOUNT_MANAGE = true,
				BANK_ACCOUNT_WITHDRAW = true,
				BANK_ACCOUNT_DEPOSIT = true,
				BANK_ACCOUNT_TRANSACTIONS = true,
				BANK_ACCOUNT_BILL = true,
				BANK_ACCOUNT_BALANCE = true,
				JOB_MANAGE_EMPLOYEES = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				TABLET_TWEET = true,
				FLEET_VEHICLES_0 = true,
				FLEET_MANAGEMENT = true,
			},
		},
	},
})

table.insert(_defaultJobData, {
	Type = "Company",
	LastUpdated = 1784524361,
	Id = "ottos",
	Name = "Ottos Auto's",
	Salary = 700,
	SalaryTier = 1,
	Grades = {
		{
			Id = "mechanic",
			Name = "Mechanic",
			Level = 1,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				TABLET_TWEET = false,
				FLEET_VEHICLES_0 = true,
			},
		},
		{
			Id = "headmechanic",
			Name = "Head Mechanic",
			Level = 2,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				FLEET_VEHICLES_0 = true,
			},
		},
		{
			Id = "owner",
			Name = "Owner",
			Level = 99,
			Permissions = {
				JOB_MANAGEMENT = true,
				BANK_ACCOUNT_MANAGE = true,
				BANK_ACCOUNT_WITHDRAW = true,
				BANK_ACCOUNT_DEPOSIT = true,
				BANK_ACCOUNT_TRANSACTIONS = true,
				BANK_ACCOUNT_BILL = true,
				BANK_ACCOUNT_BALANCE = true,
				JOB_MANAGE_EMPLOYEES = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				TABLET_TWEET = true,
				FLEET_VEHICLES_0 = true,
				FLEET_MANAGEMENT = true,
			},
		},
	},
})

table.insert(_defaultJobData, {
	Type = "Company",
	LastUpdated = 1784524361,
	Id = "bennys",
	Name = "Benny's",
	Salary = 700,
	SalaryTier = 1,
	Grades = {
		{
			Id = "mechanic",
			Name = "Mechanic",
			Level = 1,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				TABLET_TWEET = false,
				FLEET_VEHICLES_0 = true,
			},
		},
		{
			Id = "headmechanic",
			Name = "Head Mechanic",
			Level = 2,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				FLEET_VEHICLES_0 = true,
			},
		},
		{
			Id = "owner",
			Name = "Owner",
			Level = 99,
			Permissions = {
				JOB_MANAGEMENT = true,
				BANK_ACCOUNT_MANAGE = true,
				BANK_ACCOUNT_WITHDRAW = true,
				BANK_ACCOUNT_DEPOSIT = true,
				BANK_ACCOUNT_TRANSACTIONS = true,
				BANK_ACCOUNT_BILL = true,
				BANK_ACCOUNT_BALANCE = true,
				JOB_MANAGE_EMPLOYEES = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				TABLET_TWEET = true,
				FLEET_VEHICLES_0 = true,
				FLEET_MANAGEMENT = true,
			},
		},
	},
})

table.insert(_defaultJobData, {
	Type = "Company",
	LastUpdated = 1784524361,
	Id = "paleto_tuners",
	Name = "Paleto Tuners",
	Salary = 700,
	SalaryTier = 1,
	Grades = {
		{
			Id = "mechanic",
			Name = "Mechanic",
			Level = 1,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				TABLET_TWEET = false,
				FLEET_VEHICLES_0 = true,
			},
		},
		{
			Id = "headmechanic",
			Name = "Head Mechanic",
			Level = 2,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				FLEET_VEHICLES_0 = true,
			},
		},
		{
			Id = "owner",
			Name = "Owner",
			Level = 99,
			Permissions = {
				JOB_MANAGEMENT = true,
				BANK_ACCOUNT_MANAGE = true,
				BANK_ACCOUNT_WITHDRAW = true,
				BANK_ACCOUNT_DEPOSIT = true,
				BANK_ACCOUNT_TRANSACTIONS = true,
				BANK_ACCOUNT_BILL = true,
				BANK_ACCOUNT_BALANCE = true,
				JOB_MANAGE_EMPLOYEES = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				TABLET_TWEET = true,
				FLEET_VEHICLES_0 = true,
				FLEET_MANAGEMENT = true,
			},
		},
	},
})

table.insert(_defaultJobData, {
	Type = "Company",
	LastUpdated = 1784524361,
	Id = "dreamworks",
	Name = "Dreamworks",
	Salary = 700,
	SalaryTier = 1,
	Grades = {
		{
			Id = "mechanic",
			Name = "Mechanic",
			Level = 1,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				TABLET_TWEET = false,
				FLEET_VEHICLES_0 = true,
			},
		},
		{
			Id = "headmechanic",
			Name = "Head Mechanic",
			Level = 2,
			Permissions = {
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				FLEET_VEHICLES_0 = true,
			},
		},
		{
			Id = "owner",
			Name = "Owner",
			Level = 99,
			Permissions = {
				JOB_MANAGEMENT = true,
				BANK_ACCOUNT_MANAGE = true,
				BANK_ACCOUNT_WITHDRAW = true,
				BANK_ACCOUNT_DEPOSIT = true,
				BANK_ACCOUNT_TRANSACTIONS = true,
				BANK_ACCOUNT_BILL = true,
				BANK_ACCOUNT_BALANCE = true,
				JOB_MANAGE_EMPLOYEES = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
				TABLET_TWEET = true,
				FLEET_VEHICLES_0 = true,
				FLEET_MANAGEMENT = true,
			},
		},
	},
})
