table.insert(_defaultJobData, {
	Type = "Company",
	LastUpdated = 1784524361,
	Id = "saints",
	Hidden = true,
	Name = "The Saints",
	Salary = 0,
	SalaryTier = 1,
	Grades = {
		{
			Id = "leader",
			Name = "Leader",
			Level = 99,
			Permissions = {
				JOB_MANAGEMENT = true,
				BANK_ACCOUNT_MANAGE = true,
				BANK_ACCOUNT_WITHDRAW = true,
				BANK_ACCOUNT_DEPOSIT = true,
				BANK_ACCOUNT_TRANSACTIONS = true,
				BANK_ACCOUNT_BILL = true,
				BANK_ACCOUNT_BALANCE = true,
				JOB_MANAGE_EMPLOYEES = true,
				JOB_HIRE = true,
				JOB_FIRE = true,
				JOB_DOORS = true,
				JOB_STORAGE = true,
				JOB_CRAFTING = true,
			},
		},
	},
})
